global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'titanovax-monitor'

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ML Brain service
  - job_name: 'ml-brain'
    static_configs:
      - targets: ['ml-brain:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # MT5 Executor service
  - job_name: 'mt5-executor'
    static_configs:
      - targets: ['mt5-executor:8002']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Orchestration service
  - job_name: 'orchestration'
    static_configs:
      - targets: ['orchestration:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # PostgreSQL exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Nginx exporter
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Custom recording rules
recording_rules:
  - name: trading_metrics
    rules:
      - record: trading:profit_rate
        expr: rate(trading_profit_total[5m])
      
      - record: trading:win_rate
        expr: rate(trading_wins_total[5m]) / rate(trading_trades_total[5m])
      
      - record: trading:drawdown_percent
        expr: (trading_equity_max - trading_equity_current) / trading_equity_max * 100
      
      - record: ml:prediction_accuracy
        expr: rate(ml_predictions_correct_total[5m]) / rate(ml_predictions_total[5m])
      
      - record: ml:model_confidence_avg
        expr: avg(ml_model_confidence) by (model_type)

# Custom alerting rules
alerting_rules:
  - name: trading_alerts
    rules:
      - alert: HighDrawdown
        expr: trading:drawdown_percent > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High drawdown detected"
          description: "Current drawdown is {{ $value }}%"
      
      - alert: TradingSystemDown
        expr: up{job=~"ml-brain|mt5-executor|orchestration"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Trading system component is down"
          description: "{{ $labels.job }} has been down for more than 2 minutes"
      
      - alert: LowPredictionAccuracy
        expr: ml:prediction_accuracy < 0.5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low ML prediction accuracy"
          description: "Model accuracy is below 50%"
      
      - alert: HighRiskExposure
        expr: trading:risk_exposure_percent > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High risk exposure"
          description: "Current risk exposure is {{ $value }}%"
      
      - alert: DatabaseConnectionFailed
        expr: postgres_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Database connection failed"
          description: "PostgreSQL database is not accessible"
      
      - alert: RedisConnectionFailed
        expr: redis_up == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Redis connection failed"
          description: "Redis cache is not accessible"
      
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 90%"
      
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 90%"
      
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space"
          description: "Disk space is below 10%"
      
      - alert: MT5ConnectionFailed
        expr: mt5_connection_status == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "MT5 connection failed"
          description: "Connection to MT5 broker is lost"
      
      - alert: UnusualTradingVolume
        expr: rate(trading_volume_total[5m]) > 10 * avg_over_time(rate(trading_volume_total[1h])[1h])
        for: 5m
        labels:
          severity: info
        annotations:
          summary: "Unusual trading volume"
          description: "Trading volume is significantly higher than average"
      
      - alert: ModelRetrainRequired
        expr: time() - ml_model_last_training_timestamp > 86400 * 2
        for: 1h
        labels:
          severity: info
        annotations:
          summary: "Model retraining required"
          description: "ML model hasn't been retrained in over 2 days"